version: 0.2

phases:
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - yarn run build
#  post_build:
#    commands:
#      - aws cloudfront create-invalidation --distribution-id EXXXXXXX --paths "/*"
batch:
  fast-fail: false
artifacts:
  files:
    - '**/*'
  base-directory: dist
cache:
  paths:
    - /tmp/node_modules.tar