version: 0.2

phases:
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - yarn generate
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id E19NR6ENBBQKIZ --paths "/*"
artifacts:
  files:
    - '**/*'
  base-directory: dist
cache:
  paths:
    - /tmp/node_modules.tar